language: python

python:
 - "2.7"
 - "3.6"

script:
 - python MainMenu.py < MainMenuTest.txt
 - python Character.py

#before_install:
# - pip install coverage
#  - cd python

#script:
#  - nosetests -v --with-coverage
